# 服务配置
server:
  port: 8085

# 关闭activiti登录验证


# Spring相关配置
spring:
  ##数据库连接信息
  datasource:
    # 数据源配置
    url: jdbc:mysql://127.0.0.1:3306/activiti?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

    # SQLException: XAER_INVAL: Invalid arguments (or unsupported command)问题
    xa:
      properties:
        pinGlobalTxToPhysicalConnection: true
        useServerPrepStmts: true

  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  application:
    # 注册应用名
    name: actdemo
  mvc:
    # 静态资源路径
    static-path-pattern: /static/**
  # 参考配置https://www.cnblogs.com/liaojie970/p/8857710.html
  activiti:
    # 自动建表
    database-schema: ACTIVITI
    database-schema-update: true
    history-level: full
    db-history-used: true
    
# Activiti默认使用Spring的security
security:
  basic:
    enabled: false
