server:
  port: 8090

spring:
  application:
    name: kafka-producer

  kafka:
    producer:
      # spring.kafka.producer.bootstrap-servers=192.168.1.130:9092,192.168.1.101:9093,192.168.1.101:9094
      bootstrap-servers: 192.168.25.131:9092

      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

# topic
kafka:
  app:
    topic:
      foo: test-topic




